on:
  push:
    branches: [ "main" ]
    paths:
      - backend/
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Run deployment script on port
      shell: bash
      run: |
        cd backend
        chmod +x deploy.sh
        ./deploy.sh
